'on':
  - push
jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote
    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          definition-file: Sample_testin-alloftesting-API-1.0.0-resolved.yaml

